"""
attestation_response_simulator.py

Purpose: Reads the Pending attestation records generated by
attestation_generator.py and simulates owner responses. In a real
company this data would come from actual emails or a ticketing
system integration. Here we simulate it with weighted randomness
so the pipeline has realistic data to work with.

Weighting used: 70 percent Approved, 10 percent Rejected,
20 percent No Response. These numbers are documented in
docs/attestation_records.json so anyone reviewing the repo
understands this is simulated data, not a live integration.

Run this from the project root with the venv activated:
python scripts/attestation_response_simulator.py
"""

import json
import random
from datetime import datetime, timedelta

INPUT_JSON = "docs/attestation_records.json"
OUTPUT_JSON = "docs/attestation_results.json"

OUTCOME_WEIGHTS = {
    "Approved": 0.70,
    "Rejected": 0.10,
    "No Response": 0.20,
}


def simulate_response(record):
    outcome = random.choices(
        population=list(OUTCOME_WEIGHTS.keys()),
        weights=list(OUTCOME_WEIGHTS.values()),
        k=1,
    )[0]

    record["AttestationStatus"] = outcome

    if outcome in ("Approved", "Rejected"):
        date_sent = datetime.strptime(record["DateSent"], "%Y-%m-%d")
        response_delay = random.randint(1, 25)
        response_date = date_sent + timedelta(days=response_delay)
        record["ResponseDate"] = response_date.strftime("%Y-%m-%d")
    else:
        record["ResponseDate"] = None

    return record


def process_all_records():
    with open(INPUT_JSON, "r", encoding="utf-8") as f:
        records = json.load(f)

    updated_records = [simulate_response(r) for r in records]
    return updated_records


def save_results(records):
    with open(OUTPUT_JSON, "w", encoding="utf-8") as f:
        json.dump(records, f, indent=2)

    approved = sum(1 for r in records if r["AttestationStatus"] == "Approved")
    rejected = sum(1 for r in records if r["AttestationStatus"] == "Rejected")
    no_response = sum(1 for r in records if r["AttestationStatus"] == "No Response")

    print(f"Processed {len(records)} attestation records.")
    print(f"Approved: {approved} | Rejected: {rejected} | No Response: {no_response}")
    print(f"Saved to {OUTPUT_JSON}")


if __name__ == "__main__":
    updated_records = process_all_records()
    save_results(updated_records)